### ISSUE TITLE
getExtension error

### ISSUE THREAD

**Issue by andrevenancio** [benvanik/WebGL-Inspector#159]
Replicate:

1) Open any WebGL website (webgl1)
2) Open the console
3) past this code `document.createElement('canvas').getContext('webgl').getExtension('OES_vertex_array_object');`

you should see something rather than a null being returned if your graphics card supports vertex array object

4) enable WebGL Inspector
5) paste the same code above

You now get a `null` instead of the original object returned in step `3`..

This tool is amazing, and its a shame its not being picked up and updated...

**Comment by MintPaw** [comment]
It seems using the inspector takes away most of your extensions, it's a big issue when trying to debug multiple framebuffers since the inspector disabled WEBGL_draw_buffers.
This happens on both Chrome and Firefox.

**Comment by andrevenancio** [comment]
closing this since the repo seems to be dead.
