### ISSUE TITLE
The extension is always greyed out in Chrome

### ISSUE THREAD

**Issue by jeffsaremi** [benvanik/WebGL-Inspector#165]
or there is a trick to enabling this which I don't know.

**Comment by willeastcott** [comment]
"Works for me".

![image](https://user-images.githubusercontent.com/697563/42853093-277c0a7c-89e9-11e8-8b49-068d24bf96a2.png)

I mean, you have to click the GL button to activate the extension. I presume you're doing that?

**Comment by jeffsaremi** [comment]
i was doing it however it wouldn't give me an option to debug. After I left this for sometime, going back to the page i now see the icon changed color and I could click on it to see the UI button. I am not able to reproduce so I'm closing this.
